name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.9"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install sphinx furo

      - name: build doc
        run: |
          source .venv/bin/activate
          alias python3=python
          sh ./scripts/build.sh
